Repository arendt9797/MapMory, pull requests merged in 2025-03, with the labels that each got.

#26 Refactor:#18 SignUpPage 리팩토링
  src/components/features/auth/AuthForm.jsx
  src/components/features/auth/AuthInput.jsx
  src/constants/formFields.js
  src/lib/hooks/useSignUpForm.js
  src/lib/utils/authValidate.js
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
  src/stores/authStore.js
Labels: ✨Feature, 🎨Styles, ⚒️Refactor

#25 Feature/#24: Button 공통 컴포넌트 구현
  src/components/commons/Button.jsx
  src/index.css
Labels: ✨Feature

#23 Feature/#22: text title 공통 컴포넌트 구현
  src/components/commons/Text.jsx
  src/components/commons/Title.jsx
Labels: ✨Feature

#29 Refactor/#27 로그인 페이지 리팩토링
  src/app/ProtectedRouter.jsx
  src/app/Router.jsx
  src/components/features/auth/AuthForm.jsx
  src/lib/hooks/useSignInForm.js
  src/pages/SignInPage.jsx
  src/stores/authStore.js
Labels: ✨Feature, 🎨Styles, ⚒️Refactor

#21 Feature/#6: My Plan Page
  package.json
  pnpm-lock.yaml
  src/components/features/myPlanPage/CardContainer.jsx
  src/components/features/myPlanPage/ContentsContainer.jsx
  src/components/features/myPlanPage/GridBox.jsx
  src/components/features/myPlanPage/MyPlanCard.jsx
  src/components/features/myPlanPage/StatusPage.jsx
  src/constants/queryKeys.js
  src/constants/storageKey.js
  src/lib/apis/planApi.js
  src/lib/hooks/useMyPlan.js
  src/lib/utils/processPlansData.js
  src/main.jsx
  src/pages/MyPlanPage.jsx
Labels: ✨Feature, ⚙️Setting

#33 Refactor/#31: MyPlanPage_Refactoring
  src/components/features/myPlanPage/StatusPage.jsx
Labels: ⚒️Refactor

#28 Feature/#5 detail plan page
  index.html
  package.json
  pnpm-lock.yaml
  src/components/features/DetailPlanMap.jsx
  src/constants/naverMap.js
  src/constants/queryKeys.js
  src/constants/supabaseConstants.js
  src/lib/apis/planApi.js
  src/lib/hooks/useDetailMapcreate.js
  src/lib/hooks/useDetailPlan.js
  src/lib/utils/.gitkeep
  src/lib/utils/convertToMapPoint.js
  src/pages/DetailPlanPage.jsx
Labels: ✨Feature, ⚙️Setting

#37 Bugfix/#36 새로고침 로그아웃 버그 문제
  src/App.jsx
  src/components/layouts/AuthHeader.jsx
  src/lib/providers/AuthProvider.jsx
  src/stores/authStore.js
Labels: 🐞BugFix

#43 chore:#42 change import, PR Template
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/features/auth/AuthForm.jsx
Labels: 🐞BugFix

#39 Feature/#7 create plan page outline
  index.html
  package.json
  pnpm-lock.yaml
  src/app/Router.jsx
  src/components/features/create-plan-page/CreatePlanCreated.jsx
  src/components/features/create-plan-page/CreatePlanCreation.jsx
  src/components/features/create-plan-page/NaverMap.jsx
  src/constants/formFields.js
  src/constants/naverMap.js
  src/lib/apis/mutatePlans.js
  src/lib/apis/naverGetRoadAddress.js
  src/lib/apis/supabaseGetUserId.js
  src/lib/hooks/create-plan/useBeforeConfirmedMarker.js
  src/lib/hooks/create-plan/useConfirmedMarkers.js
  src/lib/hooks/create-plan/useCreatePlanCreation.js
  src/lib/hooks/create-plan/useHandleDeleteMarker.js
  src/lib/hooks/create-plan/useMapClickListner.js
  src/lib/hooks/create-plan/useMutatePlans.js
  src/lib/hooks/create-plan/useNaverMap.js
  src/lib/hooks/create-plan/useRoadAddress.js
  src/lib/hooks/create-plan/useUserId.js
  src/lib/utils/calculateMinDate.js
  src/lib/utils/makeMarkerIcon.js
  src/pages/CreatePlanPage.jsx
  tailwind.config.js
Labels: ✨Feature, ⚒️Refactor

#41 update:#38 마커 클릭시 해당 메모 렌더
  src/components/features/DetailPlanMap.jsx
  src/constants/naverMap.js
  src/pages/DetailPlanPage.jsx
Labels: ✨Feature

#47 Feature/#44 map center and invalidation
  index.html
  src/components/features/create-plan-page/CreatePlanCreated.jsx
  src/components/features/create-plan-page/CreatePlanCreation.jsx
  src/lib/apis/naverGetJibunAddress.js
  src/lib/hooks/create-plan/useCreatePlanCreation.js
  src/lib/hooks/create-plan/useJibunAddress.js
  src/lib/hooks/create-plan/useMutatePlans.js
  src/lib/hooks/create-plan/useNaverMap.js
  src/lib/hooks/create-plan/useRoadAddress.js
  src/pages/CreatePlanPage.jsx
  src/ui/.gitkeep
Labels: ✨Feature

#50 BugFix/#49: relogin_cached_data_issue
  src/components/layouts/AuthHeader.jsx
Labels: 🐞BugFix

#55 feature:#51 랜덤 이미지 썸네일
  public/thumbnail/thumbnail1.jpg
  public/thumbnail/thumbnail10.jpg
  public/thumbnail/thumbnail2.jpg
  public/thumbnail/thumbnail3.jpg
  public/thumbnail/thumbnail4.jpg
  public/thumbnail/thumbnail5.jpg
  public/thumbnail/thumbnail6.jpg
  public/thumbnail/thumbnail7.jpg
  public/thumbnail/thumbnail8.jpg
  public/thumbnail/thumbnail9.jpg
  src/components/features/myPlanPage/MyPlanCard.jsx
  src/constants/thumbnails.js
Labels: ✨Feature

#54 Refactor/#52: refactoring auth page
  package.json
  pnpm-lock.yaml
  src/components/features/auth/AuthForm.jsx
  src/components/features/auth/AuthInput.jsx
  src/components/layouts/AuthHeader.jsx
  src/lib/apis/naverGetJibunAddress.js
  src/lib/apis/planApi.js
  src/lib/apis/supabaseGetUserId.js
  src/lib/hooks/create-plan/useMutatePlans.js
  src/lib/hooks/useSignUpForm.js
  src/pages/SignUpPage.jsx
Labels: 🎨Styles, ⚒️Refactor

#57 refactor:#46 스타일링 및 에러 해결
  src/components/features/DetailPlanList.jsx
  src/components/features/DetailPlanMap.jsx
  src/lib/apis/planApi.js
  src/lib/hooks/useDetailMapcreate.js
  src/pages/DetailPlanPage.jsx
  src/pages/SignUpPage.jsx
Labels: 🐞BugFix, 🎨Styles, ⚒️Refactor

#66 bugfix:#65 detailPlanPage 정렬 문제 해결
  src/pages/DetailPlanPage.jsx
Labels: 🐞BugFix
